application: freedom-io-app
version: 1
threadsafe: true
api_version: 1
default_expiration: 1d

runtime: python27

handlers:

# static
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# dynamic
- url: /facebook/.*
  script: facebook.application
  secure: always

- url: /googleplus/.*
  script: googleplus.application
  secure: always

- url: /twitter/.*
  script: twitter.application
  secure: always

- url: /wordpress/.*
  script: wordpress.application
  secure: always

- url: /(migrate|migration/.*)
  script: migrations.application
  secure: always

- url: /_ah/queue/.*
  script: tasks.application
  login: admin

- url: /
  script: main.application
  secure: always

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
# don't need anything in the submodule subdirs, especially since
# webapp-improved/lib has over 1k files!
- ^google-api-python-client/(docs|samples|tests)/.*
- ^httplib2_module/(doc|python3|ref|test).*
- ^webutil/webapp-improved/.*/.*
