application: freedom-io-app
version: 1
threadsafe: true
api_version: 1
default_expiration: 1d

runtime: python27

libraries:
- name: ssl
  version: latest

handlers:

# static
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# dynamic
- url: /blogger/.*
  script: blogger.application
  secure: optional
  login: required

- url: /dropbox/.*
  script: dropbox.application
  secure: optional

- url: /facebook/.*
  script: facebook.application
  secure: optional

- url: /googleplus/.*
  script: googleplus.application
  secure: optional
  login: required

- url: /tumblr/.*
  script: tumblr.application
  secure: optional

- url: /twitter/.*
  script: twitter.application
  secure: optional

- url: /wordpress_rest/.*
  script: wordpress_rest.application
  secure: optional

- url: /wordpress_xmlrpc/.*
  script: wordpress_xmlrpc.application
  secure: optional

- url: /(migrate|migration/.*)
  script: migrations.application
  secure: optional

- url: /_ah/queue/.*
  script: tasks.application
  login: admin

- url: /
  script: main.application
  secure: optional

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
# don't need anything in the submodule subdirs, especially since
# webapp-improved/lib has over 1k files!
- gdata-python-client/(pydocs|samples|tests)/.*
- google-api-python-client/(docs|samples|tests)/.*
- httplib2_module/(doc|python3|ref|test).*
- webutil/webapp-improved/.*/.*
- oauthlib_module/(docs|tests)/.*
- python-gflags/(debian|tests)/.*
- requests_module/docs/.*
- requests_oauthlib_module/tests/.*

